name: tmdb_challenge
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  go_router: ^9.0.0
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.18.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0

dependency_overrides:
  collection: ^1.17.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
